### ISSUE TITLE
SMAPI 3.0 updates needed

### ISSUE THREAD

**Issue by rikai** [OfficialTab/walk-through-trellis#4]
Getting the following errors when launching on the latest stable version of SMAPI and figured these [should be addressed with SMAPI 3.0 on the horizon](https://stardewvalleywiki.com/Modding:Migrate_to_SMAPI_3.0).

>[SMAPI] walkthroughtrellis will break in the upcoming SMAPI 3.0 (legacy events are deprecated since SMAPI 2.9).

Looks like PR #3 may address this, but it hasn't been merged or pushed to Nexus yet, so consider this a friendly reminder issue for tracking the progress of that. :)

**Comment by OfficialTab** [comment]
Updated.
